name: EnchantRemover
version: '2.0'
main: me.aricius.enchantremover.Enchantremover
authors: [ Aricius ]
api-version: 1.17
permissions:
  unenchanter.use:
    description: Pou탑ij NPC na spawnu.
  obchodnik.use:
    description: Pou탑ij NPC na spawnu.
commands:
  unenchant:
    description: Pou탑ij NPC na spawnu.
  obchodnik:
    description: Pou탑ij NPC na spawnu.
