name: EnchantRemover
version: '1.5'
main: me.aricius.enchantremover.Enchantremover
authors: [ Aricius ]
api-version: 1.17
permissions:
  unenchanter.use:
    description: Použij NPC na spawnu.
commands:
  unenchant:
