name: EnchantRemover
version: 1.0
main: me.aricius.enchantremover.Enchantremover
authors: [Aricius, Kaykka_]
depend: [EndlessCrystal]
api-version: 1.19

commands:
  kouzelnik:
    description: Reload config of Kouzelník.
permissions:
  kouzelnik.reload:
    default: op
